# -*- coding: utf-8 -*-
"""Pyassignment -2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U5spLaKx-GpfcZ1u7DIJ-thi93MmJJZ4

PYTHON ASSESSMENT-2
(PATTERNS)

#1)
"""

#     *
#    **
#   ***
#  ****
# *****

#while loop
i=1
j = 5
while i in range(1,6):
  print(' '*j+i*'*')
  j-=1
  i+=1

#for loop
j=5
for i in range(1,6):
  print(' '*j + i*'*')
  j-=1

"""#2)"""

#     *
#    ***
#   *****
#  *******
# *********

# while loop
i = 1
while (i<=9):
  if((i%2)!=0):
   print(' '*(9-i//2) + i*'*')
  i+=1

#for loop

j=4
for i in range(1,10,2):
  print(' '*j+i*'*')
  j-=1

"""#3)"""

# *********
#  *******
#   *****
#    ***
#     *

# #while loop
i= 9
while(i>=1):
  if((i%2)!=0):
    print(' '*(9-i//2)+i*'*')
  i-=1

#for loop
j =1
for i in range(9,0,-2):
  print(' '*(j+1)+ i*'*')
  j+=1

"""#4)"""

#     *
#    ***
#   *****
#  *******
# *********
#  *******
#   *****
#    ***
#     *

#while loop
a=1
b=4
while(b>=0):
  print(' '*b+'*'*a)
  a+=2
  b-=1
a=7
b=1
while(b<=4):
  print(' '*b+'*'*a)
  a-=2
  b+=1

# for loop
j = 4
for i in range(1,10,2):
  print(' '*j+i*'*')
  j-=1

k= 1
for a in range(7,0,-2):
  print(' '*k+a*'*')
  k+=1

"""#5)"""

# 2 9
# 3 8
# 4 7
# 5 6
# 6 5
# 7 4
# 8 3
# 9 2
# 10 1

#while loop
i = 2
while(i<=10):
  print(i,11-i)
  i+=1

# for loop
for i in range(2,11):
  print(i,11-i)

"""#6)"""

# while loop
i = 1
while(i<=5):
  j = 1
  while(j<=i):
   print(i,end='')
   j+=1
  print()
  i+=1

# for loop
for i in range(1,6):
  for j in range(1,i+1):
    print(i,end='')
  print()

"""#7)"""

# 54321
# 4321
# 321
# 21
# 1

# while loop
i = 5
while(i>=0):
  j = i
  while(j>=1):
   print(j,end='')
   j-=1
  i-=1
  print()

# for loop
for i in range(5,0,-1):
  for j in range(i,0,-1):
    print(j,end='')
  print()

"""#8)"""

# 1
# 2 3
# 4 5 6
# 7 8 9 10
# 11 12 13 14 15

# while loop

i = 1
o = 1
while(i<=5):
  j = 1
  while(j<=i):
    print(o,end=' ')
    j+=1
    o+=1
  print()
  i+=1

# for loop
o = 1
for i in range(1,6):
  for j in range(i):
   print(o,end=' ')
   o+=1
  print()

"""#9)"""

#1 2 3 4 5
# 6 7 8 9
#10 11 12
#13 14
#15

# while loop

i = 5
o = 1
while(i>=1):
  j=i
  while(j>=1):
    print(o,end=' ')
    j-=1
    o+=1
  print()
  i-=1

# for loop
o = 1
for i in range(5,0,-1):
  for j in range(i):
    print(o,end=' ')
    o+=1
  print()

"""#10)"""

# 0 x 9 + 8 = 8
# 9 x 9 + 7 = 88
# 98 x 9 + 6 = 888
# 987 x 9 + 5 = 8888
# 9876 x 9 + 4 = 88888
# 98765 x 9 + 3 = 888888
# 987654 x 9 + 2 = 8888888
# 9876543 x 9 + 1 = 88888888
# 98765432 x 9 + 0 = 888888888

n=9
j=7
c=''
i=10
if(i==10):
    s='0'
    print(f'{int(s)} x {n} + 8 = {int(s)*n+8}')
    i-=1
for i in range(9,1,-1):
  c=c+str(i)
  m=int(c)
  print(f'{m} x {n} + {j}= {(m*n)+j}')
  j-=1

"""#11)"""

# 1
# 2 4
# 3 6 9
# 4 8 12 16
# 5 10 15 20 25
# 6 12 18 24 30 36
# 7 14 21 28 35 42 49
# 8 16 24 32 40 48 56 64
# 9 18 27 36 45 54 63 72 81
# 10 20 30 40 50 60 70 80 90 100

# for loop

for i in range(1,11):
  for j in range(i):
    print(i*(j+1),end=' ')
  print()

# while loop
i = 1
o = 1
while(i<=10):
  j = 1
  while(j<=i):
    print(j*(i),end=' ')
    j+=1
    o+=1
  print()
  i+=1

"""#12)"""

#             1
#           2 3
#         4 5 6
#      7 8 9 10
# 11 12 13 14 15

l = 11
o = 1
for i in range(1,6):
    print(' '*l,end='')
    for j in range(1,i+1):
      print(o,end=' ')
      o+=1
      l-=1
    print()

"""#13)"""

# 13.

# A
# A A
# A A A
# A A A A
# A A A A A

# for loop

j = 1
for i in range(1,6):
  print('A '*j)
  j+=1

# while loop
i = 1
while i in range(1,6):
  j = 1
  while j in range(1,i+1):
    print('A',end=' ')
    j+=1
  i+=1
  print()

"""#14)"""

# A
# AB
# ABC
# ABCD
# ABCDE

# while loop
i = 1
while(i<=5):
  j = 1
  while(j<=i):
    alpha = chr(ord('A') + j - 1)
    print(alpha,end='')
    j+=1
  i+=1
  print()

# for loop
for i in range(1,6):
  for j in range(1,i+1):
    a = chr(ord('A')+j-1)
    print(a,end='')
  print()

"""#15)"""

#   A
#  ABC
# ABCDE

# while loop
o = 3
i = 1
while i in range(1,6):
  print(' '*o, end='')
  j = 1
  while j in range(1,i+1):
    alpha = chr(ord('A')+ j-1)
    print(alpha,end='')
    j+=1
  i+=2
  o-=1
  print()

# for loop
k = 3
for i in range(1,6,2):
  print(' '*k,end='')
  for j in range(1,i+1):
    a = chr(ord('A')+j-1)
    print(a,end='')
  k-=1
  print()

"""#16)"""

# A
# BC
# DEF
# IJKL
# MNOPQ
# RSTUVW

i = 1
l = 1
while(i<=6):
  j = 1
  while(j<=i):
    if((l==7) or (l==8)):
        l+=1
        continue
    a = chr(ord('A')+ l -1)
    print(a,end='')
    j+=1
    l+=1
  print()
  i+=1

"""#17)"""

#   A
#  BCD
# EFGHI

# for loop
l = 2
o = 1
for i in range(1,6,2):
  print(' '*l,end='')
  for k in range(1,i+1):
    a = chr(ord('A')+o-1)
    print(a,end='')
    l-=1
    o+=1
  print()

# while loop
i = 1
l = 2
while(i<=6):
  print(' '*l,end='')
  j = 1
  while(j<=i):
    a =chr(ord('A')+i +j-2)
    print(a,end='')
    j+=1
  print()
  i+=2
  l-=1