# -*- coding: utf-8 -*-
"""Pyassignment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y6SmWuVID1GfJuXqmlSuGdaj8fFbooGX

#PYTHON ASSESSMENT
"""

# 1.a
#Solve

p,s = 9,8
p *=s
p

# b
p,s = 9,8
p -= s
p

# c
p,s = 9,8
p= p/s
p

# d
p,s = 9,8
p >>=s
p

# e
p,s = 9,8
p= p<<s
p

# 2.
# Example of a multiline comment?

''' Hello there,
This is an example
of multiline comment '''

a = 5
print(a)

# 3.
#Solve

S, t = 3, 4
S %= t
S

# 4.a
#Solve

A = 8
B = 10
A & B          # & - bitwise operator

# b
A = 8
B = 10
A or B        # or - logical operator

# 5.
# Command to find the length of the string?

a = 'Hello world'
len(a)                #len command

# 6. Which  of the following is an invalid identifier?
# a. a123 - valid
# b. _n_9 - valid
# c. All_is_well - valid
# d. aB1! -    invalid       (because it contains special character '!' which is not allowed)

# 7. Give an example for each of these for a 4 words sentence -
# Title Case
a = 'PythonIsAPopularLanguage'
# Camel Case
a = 'pythonIsAPopularlanguage'
# Snake Case
a = 'python_is_a_popular_language'

# 8.
#  What is the output for b*(c+a) ?
a, b , c = 1, 2, 3
b*(c+a)

# 9.
# Print ‘are’ only
str1 = 'how are you'
print(str1[4:7])

# 10.
# Write the command to get only imaginary number in the code below?
import cmath
x = 5
y = 5
z = complex(x,y)
z = 5+5j
z.imag

# 11.a

bool( { } )             #empty set has no value hence it is a false condition

# b
bool(False)

# 12.a
# What are the data types of following respectively?
a = (1,[2,3])
type(a)                        #it is a tuple because it is enclosed in parenthesis

# b
b = [1,2,'f']
type(b)                    #it is a list because it is enclosed in '[]' brackets

# c
c = 'hey1'
type(c)                  #items enclosed in '' or "" are strings

# d
d = 123
type(d)

# e
e = {(1,2),['e']}
type(e)                    #list datatype is not allowed in set

#13.
#What is the output for the code below?
print(10 == 9)             #false because it checks equality of both integers

# 14.
# What is the output for the below code?
quantity = 3
itemno = 567
price = 49.95
myorder = "I want to pay {2} dollars for {0} pieces of item {1}."
print(myorder.format(quantity, itemno, price))                     #format method

# 15.
# Convert the words ‘miss’ and ‘python’ to ‘mam’ and ‘C’ respectively without redeclaring the string?
str2 = 'hey miss! Welcome to python'
str2 = str2.replace('miss','mam')
str2 = str2.replace('python','C')               #using .replace method of tuple
str2

# 16.a
# Convert the string to title case and lower case?
Str3 = 'HYderabaD'
#Title case
Str3.title()

# b
# lower case
Str3.lower()

# 17.a
# Print how many number of ‘ A ‘ / ‘ a ‘  are there in the string without counting manually?
Str4 = 'All apples are red in color and round in shape'
# 'A'
Str4.count('A')

# b
# 'a'
Str4.count('a')

# 18.
# What is the output for the code below?
x = {1,2,3,4,5}
y = {4,5,6,7,8}
#print(x+y)    #error because '+' adding is not possible in set
#instead we can use union method to add content of both sets
x.union(y)

# 19.
x = {1,2,3,4,5}
y = {4,5,6,7,9}
print( x | y )                              # |(or) - bitwise operator

# 20.a
# What are the outputs for the code below?
print(0 | True)                              #True is 1

# b
print(0 == True)

# c
print('19' == 19)             #False because they are different datatypes

# 21.
# Write a python code to add first n numbers?
n =int(input('Give the number:  '))
result=0
for i in range(1,n+1):
      result+=i
print(f'Sum of first {n} numbers is = {result}')

# 22.
# Write a code to loop over the items in fruits list?

fruits = ["apple", "orange", "kiwi"]

for i in fruits:
   print(i)

 #  or

for i in range(len(fruits)):
  print(fruits[i])

# 23.Write a python code to print 6 table using for and while loop?
print('---------Using for loop:----------  ')

for i in range(1,11):
   result=6*i
   print(f'6 x {i} =  {result}')


print('--------Using while loop:-----------')

j = 1
while (j<=10):
  result=6*j
  print(f'6 x {j} = {result}')
  j+=1

# 24.
# Write a command to get the value of this 6 4 ?

6**4                            # ** using exponent, arithmetic operator

# 25.
# What are the outputs for the code below?

for x in [1, 2, 3]:
 print(x-1)

#  26.
# What is the output of print tuple[0] if tuple = ( 'abcd', 786 , 2.23, 'john', 70.2 )?
tuple = ( 'abcd', 786 , 2.23, 'john', 70.2 )
tuple[0]                    #gives index valued '0' ,numerical indices(positive index)

# 27.
# What is the output of L[-2] if L = [1,2,3]?
L = [1,2,3]
L[-2]                       #gives index valued '-2',(negative index)

# 28.
# What will be the output of the below given code?
colors = ['white', 'Black', 'Grey']
x = 'Red' not in colors
print(x)                   #use of membership operator 'not in' which says not included in list

# 29.
# Which is mutable and immutable in List and Tuple?

# LIST is Mutable because crud operations i.e create,read,update and delete are possible
# TUPLE is Immutable because crud operations are not possible

# 30.
# What is the output of tiny * 3, if tiny = [ 123, 'john' ] ?
tiny =[123,'john']
tiny*3  #duplication

# 31.
# Which is the function to check in a string that all characters are alphanumeric?
a = 'ab123'
a.isalnum()

# 32.
# What is the command line to get the output as ‘heshewe’?
a = ['he', 'she', 'we']
a =''.join(a)
a

# 33.
# What is the position of number 3?
L = [1,2,1,[3],5]
L.index([3])

# 34.
# Calculate total number of 9 in the below given list? And State the predefined function to
# calculate number of 9?

List1 = [9, 90, 99, 999, 9999]

List1.count(9)

# 35.
# What is the result of this code?
nums = [10, 9, 8, 7, 6, 5]
nums[0] = nums[1] - 5    #10 becomes 4 after this operation
if 4 in nums:
  print(nums[3])         #hence if statement is true
else:
  print(nums[4])

# 36.
# What is the result of this code?
nums = [9, 8, 7, 6, 5]
nums.append(4)          # 4 is added at the end of list as .append method is used
nums.insert(2, 11)      # 11 is added as index '2' in the list as .insert method is used
print(nums)
print(len(nums))           #Total =7

# 37.
# What is the result of this code?
list = [1, 1, 2, 3, 5, 8, 13]        #sublist [list[4]] indicates index which is 5 in list
print(list[list[4]])                 #it becomes [list[5]] which is index of 8 in list

# 38.
# Which of the following is false statement in python?
# a. int(144)==144    - True           #int to int and same number is equal
# b. int('144')==144  - True           #hence all are true except d
# c. int(144.0)==144  - True
# d. None of the above  - False

# 39.
# What is the output of
[ 1, 2, 3 ] + [ 4, 5, 6 ]           #concatenation of two lists

# 40.
# What is the command to sort a list?
list10 = [1,5,8,3,2,0]
list10.sort()                      #.sort method of list should be used
list10

# 41.
# Which of the following statements is used when a statement is required syntactically but
# you do not want any command or code to execute?
# a. break
# b. continue
# c. pass
# d. None of the above

#Ans - c. pass , it is the no operation statement, it does nothing when executed

# 42.
#  What is the result of this code?
tup = ("hi", "Python", 2)
print (type(tup))             #shows datatype
print (tup)                   #prints tuple tup content
print (tup[1:])               #indexing from 1 to end
print (tup[0:1])              #indexing from 0 and 1(excluded)
print (tup + tup)             #concatenation of tuple
print (tup * 3)               #duplication
#what is the updated tup
# tup[2] = ('hi')              #Item assignment is not possible in str

# 43.
# What is the result of this code?

for x in range(21,5,-3):
 print(x)

# 44.
# What is the result of this code?

for i in range(0,5):
 print(i)                         #break keyword will break out of the loop after the first iteration
 break;                           #Hence it only prints first value of 'i'

# 45.Program to check whether a number is even or not.

a = int(input('Give the number to check: '))

if((a%2) == 0):
  print('The number is EVEN')
else:
  print('The number is ODD')

# 46.
# Bring this output using loops.

for i in range(1,6):
  for j in range(i):
    print(i,end='')
  print()